#!/usr/bin/env bash
_kill() {
  kill -KILL "$child"
}

_term() {
  kill -TERM "$child"
}

_int() {
  kill -INT "$child"
}

#trap _kill SIGKILL
#trap _term SIGTERM
#trap _int SIGINT

# Ensure persistence mode is on so max power limit will stay adjusted
sudo nvidia-smi -pm=1
sudo nvidia-smi -pl=$(nvidia-smi -q -d power | grep "Max Power Limit" | sed "s/.*: \([0-9]\+\)\.[0-9]\+ W/\1/")
LIBVA_DRIVER_NAME=vdpau VDPAU_DRIVER=nvidia __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia exec "$@"
# Don't put DRI_PRIME, confuses apps into thinking Nouveau is used, Nvidia uses __NV_PRIME_RENDER_OFFLOAD
#child=$!
#wait "$child"
#kill -TERM "$child"
