networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3030:3000
